replicaCount: 1

image:
  repository: mypvtrepo.azurecr.io/akhil/my-image
  tag: v1.0.0

nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
  - name: my-key

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: myapp.example.com
      paths: []

resources: {}
