apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
  namespace: mynamespace
subjects:
  - kind: ServiceAccount
    name: dotnet
    namespace: mynamespace
roleRef:
  kind: Role
  name: dotnet-role
  apiGroup: rbac.authorization.k8s.io
