apiVersion : apps/v1
kind: Deployment
metadata:
  name: dotnetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vishnu
  template:
    metadata:
      labels:
        app: vishnu
    spec:
      containers:
        - name: vishnudotnet
          image: mypvtcontainer.azurecr.io/vishnutkdotnetapp
          ports:
          - containerPort: 5000
